name: MegaLinter

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write
  packages: read
  statuses: write
  issues: write
  pull-requests: write

env:
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: all
  APPLY_FIXES_MODE: commit

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Codebase
        id: lint-codebase
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: oxsecurity/megalinter@v8.1.0

      - run: |
          echo "${{ steps.lint-codebase.outcome }}"
          echo "${{ steps.lint-codebase.conclusion }}"
