name: MegaLinter

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write
  packages: read
  statuses: write
  issues: write
  pull-requests: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Codebase
        id: lint-codebase
        env:
          GITHUB_TOKEN: ${{ github.token }}
          APPLY_FIXES_EVENT: pull_request
          APPLY_FIXES_MODE: pull_request
        uses: oxsecurity/megalinter@beta